#!/usr/bin/env bash
# 线上验收上线脚本（在服务器项目目录执行）
#
# 用法：
#   cd /path/to/eshop-release-v1.0
#   OLD_MYSQL_ROOT_PASSWORD='当前root密码' bash scripts/prod-go-live.sh
#
# 可选环境变量：
#   COMPOSE_PROJECT_NAME  docker compose 项目名（若启动时用过 -p）
#   APP_PORT              对外端口，默认 8088
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
export ROOT

if [[ ! -f .env ]]; then
  echo "ERROR: .env 不存在。请先从 .env.example 复制并填写生产值。"
  exit 1
fi

if [[ -z "${OLD_MYSQL_ROOT_PASSWORD:-}" ]]; then
  echo "ERROR: 请先设置当前 MySQL root 密码："
  echo "  OLD_MYSQL_ROOT_PASSWORD='xxxx' bash scripts/prod-go-live.sh"
  exit 1
fi

if ! command -v docker >/dev/null 2>&1; then
  echo "ERROR: 未安装 docker"
  exit 1
fi

if ! command -v python3 >/dev/null 2>&1; then
  echo "ERROR: 需要 python3（用于生成 BCrypt 与抽检）"
  exit 1
fi

APP_PORT="${APP_PORT:-8088}"
COMPOSE=(docker compose)
if [[ -n "${COMPOSE_PROJECT_NAME:-}" ]]; then
  COMPOSE=(docker compose -p "${COMPOSE_PROJECT_NAME}")
fi

echo "==> [1/6] 备份 .env 并生成新密钥"
cp -a .env ".env.bak.$(date +%Y%m%d%H%M%S)"

python3 - <<'PY'
import base64, os, re, secrets, string
from pathlib import Path

root = Path(os.environ["ROOT"])
env_path = root / ".env"
text = env_path.read_text(encoding="utf-8")

def alnum(n=28):
    alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789"
    return "".join(secrets.choice(alphabet) for _ in range(n))

jwt = base64.b64encode(secrets.token_bytes(48)).decode()
mysql_pass = alnum(28)
root_pass = alnum(28)
admin_pass = alnum(20)

def set_key(src: str, key: str, value: str) -> str:
    pat = re.compile(rf"^{re.escape(key)}=.*$", re.M)
    line = f"{key}={value}"
    if pat.search(src):
        return pat.sub(line, src)
    return src.rstrip() + "\n" + line + "\n"

text = set_key(text, "JWT_SECRET", jwt)
text = set_key(text, "MYSQL_PASSWORD", mysql_pass)
text = set_key(text, "MYSQL_ROOT_PASSWORD", root_pass)
text = set_key(text, "BOOTSTRAP_ADMIN_ENABLED", "false")
text = set_key(text, "BOOTSTRAP_ADMIN_USERNAME", "admin")
text = set_key(text, "BOOTSTRAP_ADMIN_PASSWORD", admin_pass)
text = set_key(text, "BOOTSTRAP_ADMIN_NICKNAME", "系统管理员")
if "CORS_ALLOWED_ORIGIN_PATTERNS=" not in text:
    text = set_key(text, "CORS_ALLOWED_ORIGIN_PATTERNS", "https://eshop.zhuyiyuan9.top")
env_path.write_text(text, encoding="utf-8")

try:
    import bcrypt
except ImportError:
    import subprocess, sys
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "bcrypt"])
    import bcrypt

bcrypt_hash = bcrypt.hashpw(admin_pass.encode(), bcrypt.gensalt(rounds=10)).decode()
(root / ".secrets-rotated.txt").write_text(
    "# generated by prod-go-live.sh — DO NOT COMMIT\n"
    f"JWT_SECRET={jwt}\n"
    f"MYSQL_PASSWORD={mysql_pass}\n"
    f"MYSQL_ROOT_PASSWORD={root_pass}\n"
    f"BOOTSTRAP_ADMIN_PASSWORD={admin_pass}\n"
    f"ADMIN_BCRYPT={bcrypt_hash}\n",
    encoding="utf-8",
)
print("secrets -> .secrets-rotated.txt")
print("admin password:", admin_pass)
PY

# shell-export new secrets
eval "$(python3 - <<'PY'
from pathlib import Path
vals = {}
for line in Path(".secrets-rotated.txt").read_text(encoding="utf-8").splitlines():
    if "=" in line and not line.startswith("#"):
        k, v = line.split("=", 1)
        vals[k] = v
print(f"export NEW_MYSQL_PASSWORD={vals['MYSQL_PASSWORD']!r}")
print(f"export NEW_MYSQL_ROOT_PASSWORD={vals['MYSQL_ROOT_PASSWORD']!r}")
print(f"export ADMIN_BCRYPT={vals['ADMIN_BCRYPT']!r}")
print(f"export NEW_ADMIN_PASSWORD={vals['BOOTSTRAP_ADMIN_PASSWORD']!r}")
PY
)"

MYSQL_C=$(docker ps --format '{{.Names}}' | grep -E 'mysql' | head -n1 || true)
if [[ -z "${MYSQL_C}" ]]; then
  echo "ERROR: 找不到运行中的 mysql 容器"
  exit 1
fi
echo "MySQL container: ${MYSQL_C}"

echo "==> [2/6] 下架测试商品 + 轮换 admin/MySQL 密码"
docker exec -i "$MYSQL_C" mysql -uroot -p"${OLD_MYSQL_ROOT_PASSWORD}" --default-character-set=utf8mb4 eshop <<SQL
UPDATE product
SET status = 'OFF_SALE', updated_at = CURRENT_TIMESTAMP
WHERE status = 'ON_SALE'
  AND (
       name LIKE '%测试%'
    OR name LIKE '%Test%'
    OR name LIKE '%test%'
    OR name LIKE '%TEST%'
    OR name LIKE '%Smoke%'
    OR name LIKE '%smoke%'
    OR name LIKE 'Smoke Product%'
    OR name LIKE '%乱码%'
    OR name LIKE '%placeholder%'
    OR name LIKE '%PLACEHOLDER%'
    OR name LIKE '%临时%'
    OR name LIKE '%demo-test%'
    OR name LIKE '[TEST]%'
    OR name = 'lllhjvhj'
  );
UPDATE sys_user SET password_hash='${ADMIN_BCRYPT}' WHERE username='admin';
ALTER USER 'eshop'@'%' IDENTIFIED BY '${NEW_MYSQL_PASSWORD}';
ALTER USER 'root'@'%' IDENTIFIED BY '${NEW_MYSQL_ROOT_PASSWORD}';
ALTER USER 'root'@'localhost' IDENTIFIED BY '${NEW_MYSQL_ROOT_PASSWORD}';
FLUSH PRIVILEGES;
SELECT id, status, name FROM product WHERE status='ON_SALE' ORDER BY id;
SELECT COUNT(*) AS on_sale FROM product WHERE status='ON_SALE';
SQL

echo "==> [3/6] 重建并启动 backend / frontend"
"${COMPOSE[@]}" build backend frontend
"${COMPOSE[@]}" up -d

echo "==> [4/6] 等待健康检查"
for i in $(seq 1 40); do
  if curl -fsS "http://127.0.0.1:${APP_PORT}/api/actuator/health" 2>/dev/null | grep -q '"status":"UP"'; then
    echo "health UP"
    break
  fi
  sleep 3
  if [[ $i -eq 40 ]]; then
    echo "ERROR: health check timeout"
    "${COMPOSE[@]}" ps || true
    exit 1
  fi
done

echo "==> [5/6] 公开商品抽检"
python3 - <<PY
import json, re, urllib.request
raw = urllib.request.urlopen(f"http://127.0.0.1:${APP_PORT}/api/products?page=1&size=100", timeout=20).read()
data = json.loads(raw)
records = data.get("data", {}).get("records", [])
total = data.get("data", {}).get("total")
print("on_sale_total=", total)
pat = re.compile(r"测试|test|Smoke|乱码|临时|\[TEST\]|lllhjvhj", re.I)
bad = [r for r in records if pat.search(r.get("name") or "")]
print("bad_count=", len(bad))
for b in bad:
    print("BAD", b.get("id"), b.get("name"))
if bad:
    raise SystemExit(2)
print("product check OK")
PY

echo "==> [6/6] 管理员登录抽检"
python3 - <<PY
import json, urllib.request
pwd = None
for line in open(".secrets-rotated.txt", encoding="utf-8"):
    if line.startswith("BOOTSTRAP_ADMIN_PASSWORD="):
        pwd = line.split("=", 1)[1].strip()
req = urllib.request.Request(
    f"http://127.0.0.1:${APP_PORT}/api/auth/login",
    data=json.dumps({"username": "admin", "password": pwd}).encode(),
    headers={"Content-Type": "application/json"},
    method="POST",
)
with urllib.request.urlopen(req, timeout=15) as resp:
    body = json.load(resp)
assert body.get("data", {}).get("token"), body
print("admin login OK, role=", body["data"].get("role"))
PY

echo
echo "========================================"
echo "上线完成"
echo "密钥文件: $ROOT/.secrets-rotated.txt"
echo "管理员: admin / 见 .secrets-rotated.txt 中 BOOTSTRAP_ADMIN_PASSWORD"
echo "站点: https://eshop.zhuyiyuan9.top"
echo "管理端: https://eshop.zhuyiyuan9.top/admin/login"
echo "注意: JWT 已轮换，所有用户需重新登录"
echo "========================================"
